---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: backend-controller-manager
  name: managed-gitops-backend-service
  namespace: gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: backend-controller-manager
  template:
    metadata:
      labels:
        control-plane: backend-controller-manager
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
      - args:
        - --health-probe-bind-address=:18081
        - --metrics-bind-address=127.0.0.1:18080
        - --leader-elect
        - --zap-time-encoding=rfc3339nano
        - --api-export-name=gitops-api
        command:
        - gitops-service-backend
        env:
          - name: ARGO_CD_NAMESPACE
            value: ${ARGO_CD_NAMESPACE}
          - name: DB_ADDR
            value: gitops-postgresql-staging
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: gitops-postgresql-staging
                key: postgresql-password
          - name: GITOPS_IN_KCP
            value: "true"
        image: ${COMMON_IMAGE}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 18081
          initialDelaySeconds: 120
          periodSeconds: 60
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 18081
          initialDelaySeconds: 120
          periodSeconds: 30
        resources:
          limits:
            cpu: 300m
            memory: 1200Mi
          requests:
            cpu: 200m
            memory: 600Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: managed-gitops-backend-controller-manager
      terminationGracePeriodSeconds: 10
