apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: appstudio-controller-manager
  name: appstudio-controller-controller-manager
  namespace: gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: appstudio-controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: appstudio-controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
      - args:
        - --health-probe-bind-address=:8085
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        - --zap-time-encoding=rfc3339nano
        - --api-export-name=gitopsrvc-appstudio-shared
        command:
        - appstudio-controller
        env:
          - name: GITOPS_IN_KCP
            value: "true"
        image: ${COMMON_IMAGE}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8085
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8085
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 50m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: appstudio-controller-controller-manager
      terminationGracePeriodSeconds: 10
