{
 "title": "GitOps",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"gitops-core-service-controller-manager-metrics-service\"})"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "timeseries",
   "description": "Number of active and failed GitopsDeployments",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "active_gitopsDeployments", "legendFormat": "Total" },
    { "expr": "gitopsDeployments_failures", "legendFormat": "Failed" }
   ]
  },
  { "title": "Operation DB Rows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cluster-agent",
   "type": "timeseries",
   "description": "Number of Operation DB rows from cluster-agent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "operationDB_completedState", "legendFormat": "Completed" },
    { "expr": "operationDB_failedState", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Backend",
   "type": "timeseries",
   "description": "Number of Operation DB rows from backend",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "total_number_of_operationDB_rows",
     "legendFormat": "Total"
    },
    {
     "expr": "operationDB_rows_in_waiting_state",
     "legendFormat": "Waiting"
    },
    {
     "expr": "operationDB_rows_in_in_progress_state",
     "legendFormat": "In_Progress"
    },
    {
     "expr": "operationDB_rows_in_completed_state",
     "legendFormat": "Completed"
    },
    {
     "expr": "operationDB_rows_in_error_state",
     "legendFormat": "Failed"
    },
    {
     "expr": "total_operationDB_rows_in_complete_state",
     "legendFormat": "TotalCompleted"
    },
    {
     "expr": "operationDB_rows_in_non_complete_state",
     "legendFormat": "TotalNonCompleted"
    }
   ]
  },
  {
   "title": "Argo CD Application Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_app_info{namespace=\"gitops-service-argocd\",health_status!=\"\"}) by (health_status)",
       "legendFormat": "{{health_status}}"
      }
     ]
    },
    {
     "title": "Sync Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_app_info{namespace=\"gitops-service-argocd\",health_status!=\"\"}) by (sync_status)",
       "legendFormat": "{{sync_status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Controller Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"gitops-appstudio-service-controller-manager-metrics-service\"}",
       "legendFormat": "memory"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"gitops-appstudio-service-controller-manager-metrics-service\"}[1m])",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"gitops-appstudio-service-controller-manager-metrics-service\"}",
       "legendFormat": "goroutines"
      }
     ]
    }
   ]
  },
  {
   "title": "Core Service Controller Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"gitops-core-service-controller-manager-metrics-service\"}",
       "legendFormat": "memory"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"gitops-core-service-controller-manager-metrics-service\"}[1m])",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"gitops-core-service-controller-manager-metrics-service\"}",
       "legendFormat": "goroutines"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Agent Controller Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"gitops-service-agent-controller-manager-metrics-service\"}",
       "legendFormat": "memory"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"gitops-service-agent-controller-manager-metrics-service\"}[1m])",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"gitops-service-agent-controller-manager-metrics-service\"}",
       "legendFormat": "goroutines"
      }
     ]
    }
   ]
  }
 ]
}