
ALTER TABLE apicrtodatabasemapping DROP CONSTRAINT apicrtodatabasemapping_api_resource_type_api_resource_uid_d_key;

ALTER TABLE apicrtodatabasemapping DROP CONSTRAINT apicrtodatabasemapping_db_relation_type_db_relation_key_api_key;

ALTER TABLE gitopsengineinstance DROP CONSTRAINT gitopsengineinstance_namespace_name_namespace_uid_engineclu_key;

ALTER TABLE kubernetestodbresourcemapping DROP CONSTRAINT kubernetestodbresourcemapping_db_relation_type_db_relation__key;

ALTER TABLE kubernetestodbresourcemapping DROP CONSTRAINT kubernetestodbresourcemapping_kubernetes_resource_type_kube_key;
