{
 "title": "GitOps",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"gitops-core-service-controller-manager-metrics-service\"})"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "timeseries",
   "description": "Number of active and failed GitopsDeployments",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "active_gitopsDeployments", "legendFormat": "Total" },
    { "expr": "gitopsDeployments_failures", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Service Controller Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"gitops-appstudio-service-controller-manager-metrics-service\"}",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"gitops-appstudio-service-controller-manager-metrics-service\"}[1m])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"gitops-appstudio-service-controller-manager-metrics-service\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "Core Service Controller Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"gitops-core-service-controller-manager-metrics-service\"}",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"gitops-core-service-controller-manager-metrics-service\"}[1m])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"gitops-core-service-controller-manager-metrics-service\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "Service Agent Controller Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"gitops-service-agent-controller-manager-metrics-service\"}",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"gitops-service-agent-controller-manager-metrics-service\"}[1m])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"gitops-service-agent-controller-manager-metrics-service\"}",
     "legendFormat": "goroutines"
    }
   ]
  }
 ]
}