apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitops-backend-controller
  namespace: appstudio-workload-monitoring
  labels:
    control-plane: backend-controller-manager

spec:
  endpoints:
  - bearerTokenSecret:
      key: token
      name: prometheus-k8s-token-xhrjb
    interval: 15s
    path: /metrics
    port: metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - gitops
  selector:
    matchLabels:
      control-plane: backend-controller-manager
