apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: backend-controller-manager
  name: gitops-core-service-controller-manager-metrics-service
  namespace: gitops
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  # ports:
  # - name: http-metrics
  #   port: 8080
  #   protocol: TCP
  #   targetPort: 8080
  ports:
    - name: metrics
      protocol: TCP
      port: 8443
      targetPort: https

  selector:
    control-plane: backend-controller-manager
  sessionAffinity: None
  type: ClusterIP