apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- managed-gitops-backend-controller-manager-metrics-service.yaml
- managed-gitops-backend-controller-manager_serviceaccount.yaml
- managed-gitops-backend-leader-election-role.yaml
- managed-gitops-backend-leader-election-rolebinding.yaml
- managed-gitops-backend-manager-config.yaml
- managed-gitops-backend-manager-role.yaml
- managed-gitops-backend-manager-rolebinding.yaml
- managed-gitops-backend-metrics-leader.yaml
- managed-gitops-backend-proxy-role.yaml
- managed-gitops-backend-proxy-rolebinding.yaml
