---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: managed-gitops-backend-manager-role
rules:

- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentrepositorycredentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentrepositorycredentials/finalizers
  verbs:
  - update
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentrepositorycredentials/status
  verbs:
  - get
  - patch
  - update

- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentmanagedenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentmanagedenvironments/finalizers
  verbs:
  - update
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentmanagedenvironments/status
  verbs:
  - get
  - patch
  - update

- apiGroups:
  - ""
  resources:
    - namespaces
  verbs:
    - get
    - watch
    - list
- apiGroups:
  - ""
  resources:
    - secrets
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - secrets
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - ""
  resources:
    - configmaps
    - events
  verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update

- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeployments
  - operations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentsyncruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentsyncruns/finalizers
  verbs:
  - update
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentsyncruns/status
  verbs:
  - get
  - patch
  - update

- apiGroups:
  - apis.kcp.dev
  resources:
  - apiexports
  verbs:
  - get
  - list
  - watch
  
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - apis.kcp.dev
  resources:
  - apiexports/content
  verbs:
  - '*'
