# permissions for end users to edit applicationsnapshotenvironmentbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationsnapshotenvironmentbinding-editor-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - applicationsnapshotenvironmentbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - applicationsnapshotenvironmentbindings/status
  verbs:
  - get
