# permissions for end users to view applicationsnapshotenvironmentbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationsnapshotenvironmentbinding-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - applicationsnapshotenvironmentbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - applicationsnapshotenvironmentbindings/status
  verbs:
  - get
