# permissions for end users to edit applicationsnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationsnapshot-editor-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - applicationsnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - applicationsnapshots/status
  verbs:
  - get
