kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: component-a
spec:
  subdomain: component-a
  to:
    kind: Service
    name: component-a
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

