apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- managed-gitops-clusteragent-controller-manager-metrics-service.yaml
- managed-gitops-clusteragent-controller-manager_serviceaccount.yaml
- managed-gitops-clusteragent-leader-election-role.yaml
- managed-gitops-clusteragent-leader-election-rolebinding.yaml
- managed-gitops-clusteragent-manager-config.yaml
- managed-gitops-clusteragent-manager-role.yaml
- managed-gitops-clusteragent-manager-rolebinding.yaml
- managed-gitops-clusteragent-metrics-leader.yaml
- managed-gitops-clusteragent-proxy-role.yaml
- managed-gitops-clusteragent-proxy-rolebinding.yaml
