apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

# APIExport(s)
- ../appstudio-shared/config/kcp/apiexport_gitopsrvc_appstudioshared.yaml
- ../backend-shared/config/kcp/apiexport_gitopsrvc_backendshared.yaml

# APIResourceSchema(s)
- ../backend-shared/config/kcp/apiresourceschema_gitopsrvc_backendshared.yaml
- ../appstudio-shared/config/kcp/apiresourceschema_gitopsrvc_appstudioshared.yaml

# AppStudio-controller RBAC
- appstudio-controller-rbac/appstudio-controller-rbac.yaml

# Backend RBAC
- backend-rbac/managed-gitops-backend-controller-manager-metrics-service.yaml
- backend-rbac/managed-gitops-backend-controller-manager_serviceaccount.yaml
- backend-rbac/managed-gitops-backend-leader-election-rolebinding.yaml
- backend-rbac/managed-gitops-backend-leader-election-role.yaml
- backend-rbac/managed-gitops-backend-manager-config.yaml
- backend-rbac/managed-gitops-backend-manager-rolebinding.yaml
- backend-rbac/managed-gitops-backend-manager-role.yaml
- backend-rbac/managed-gitops-backend-metrics-leader.yaml
- backend-rbac/managed-gitops-backend-proxy-rolebinding.yaml
- backend-rbac/managed-gitops-backend-proxy-role.yaml

# Cluster-agent RBAC
- cluster-agent-rbac/managed-gitops-clusteragent-controller-manager-metrics-service.yaml
- cluster-agent-rbac/managed-gitops-clusteragent-controller-manager_serviceaccount.yaml
- cluster-agent-rbac/managed-gitops-clusteragent-leader-election-rolebinding.yaml
- cluster-agent-rbac/managed-gitops-clusteragent-leader-election-role.yaml
- cluster-agent-rbac/managed-gitops-clusteragent-manager-config.yaml
- cluster-agent-rbac/managed-gitops-clusteragent-manager-rolebinding.yaml
- cluster-agent-rbac/managed-gitops-clusteragent-manager-role.yaml
- cluster-agent-rbac/managed-gitops-clusteragent-metrics-leader.yaml
- cluster-agent-rbac/managed-gitops-clusteragent-proxy-rolebinding.yaml
- cluster-agent-rbac/managed-gitops-clusteragent-proxy-role.yaml

# Workloads
- managed-gitops-appstudio-controller-deployment.yaml
- managed-gitops-backend-deployment.yaml
- managed-gitops-clusteragent-deployment.yaml
- postgresql-staging/postgresql-staging.yaml

# Route(s)
- routes.yaml

# 'gitops-service-argocd' Namespace
- staging-cluster-resources/argo-cd-namespace.yaml


# Replace ${ARGO_CD_NAMESPACE}
patches:
- target:
    kind: Secret
    name: argocd-cluster-config
  patch: |-
    - op: replace
      path: /stringData/namespace
      value: gitops-service-argocd
- target:
    kind: Deployment
    name: managed-gitops-backend-service
    namespace: gitops
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/1/env/0/value
      value: gitops-service-argocd
- target:
    kind: Deployment
    name: managed-gitops-clusteragent-service
    namespace: gitops
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/1/env/0/value
      value: gitops-service-argocd