apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: managed-gitops
  name: managed-gitops
spec:
  ports:
  - name: server
    protocol: TCP
    port: 8090
    targetPort: 8090
  selector:
    app.kubernetes.io/name: managed-gitops