apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Create a ConfigMap based on the db-schema.sql file

namespace: gitops

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: gitops-service-dbschema
  behavior: create
  files:
  - ../../../db-schema.sql

