apiVersion: managed-gitops.redhat.com/v1alpha1
kind: GitOpsDeployment
metadata:
  name: gitops-depl
  namespace: jgw
spec:
  source:
    repoURL: https://github.com/jgwest/gitops-repository-template
    path: resources/test-data/sample-gitops-repository/environments/overlays/dev
    targetRevision: k8s-only

#  destination: 

# type: manual
  type: automated

