apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: purple-mermaid-app
  namespace: jane
#  finalizers:
#    - application.appstudio.redhat.com/finalizer
spec:
  appModelRepository:
    url: ''
  displayName: Purple Mermaid app
  gitOpsRepository:
    url: ''
status:
  conditions: []
  devfile: |
    metadata:
      attributes:
        appModelRepository.url: https://github.com/redhat-appstudio-appdata/purple-mermaid-app-rhopp-reduce-reaction
        gitOpsRepository.url: https://github.com/redhat-appstudio-appdata/purple-mermaid-app-rhopp-reduce-reaction
        gitOpsRepository.context: components/basic-node-js/base
      name: Purple Mermaid app
    projects:
    - git:
        remotes:
          origin: https://github.com/nodeshift-starters/devfile-sample.git
      name: basic-node-js
    schemaVersion: 2.1.0

