apiVersion: appstudio.redhat.com/v1alpha1
kind: SnapshotEnvironmentBinding
metadata:
  name: appa-staging-binding
  labels: 
    appstudio.application: new-demo-app
    appstudio.environment: staging
spec:
  application: new-demo-app
  environment: staging
  snapshot: my-snapshot
  components:
    - name: component-a
      configuration:
        env:
          - name: My_STG_ENV
            value: "200"
        replicas: 3
status:
  components:
    - name: component-a
      gitopsRepository: 
        url: "https://github.com/redhat-appstudio/managed-gitops"
        branch: main
        path: resources/test-data/sample-gitops-repository/components/componentA/overlays/staging
        generatedResources:
          - abc.yaml
        commitID: fdhyqtw
