---
# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitops-postgresql-staging
  namespace: gitops
type: Opaque
data:
  postgresql-password: "M0NxQ0tjWEx5Tg=="

