---
# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitops-postgresql-staging
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.16.1
    app.kubernetes.io/instance: gitops-postgresql-staging
    app.kubernetes.io/managed-by: Helm
  namespace: gitops
type: Opaque
data:
  postgresql-password: "M0NxQ0tjWEx5Tg=="

