
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentmanagedenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentmanagedenvironments/finalizers
  verbs:
  - update
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentmanagedenvironments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentrepositorycredentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentrepositorycredentials/finalizers
  verbs:
  - update
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentrepositorycredentials/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentsyncruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentsyncruns/finalizers
  verbs:
  - update
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - gitopsdeploymentsyncruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - managed-gitops.redhat.com
  resources:
  - operations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
