// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	settings "github.com/argoproj/argo-cd/v2/pkg/apiclient/settings"
)

// SettingsServiceClient is an autogenerated mock type for the SettingsServiceClient type
type SettingsServiceClient struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, in, opts
func (_m *SettingsServiceClient) Get(ctx context.Context, in *settings.SettingsQuery, opts ...grpc.CallOption) (*settings.Settings, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *settings.Settings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *settings.SettingsQuery, ...grpc.CallOption) (*settings.Settings, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *settings.SettingsQuery, ...grpc.CallOption) *settings.Settings); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*settings.Settings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *settings.SettingsQuery, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlugins provides a mock function with given fields: ctx, in, opts
func (_m *SettingsServiceClient) GetPlugins(ctx context.Context, in *settings.SettingsQuery, opts ...grpc.CallOption) (*settings.SettingsPluginsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *settings.SettingsPluginsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *settings.SettingsQuery, ...grpc.CallOption) (*settings.SettingsPluginsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *settings.SettingsQuery, ...grpc.CallOption) *settings.SettingsPluginsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*settings.SettingsPluginsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *settings.SettingsQuery, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSettingsServiceClient creates a new instance of SettingsServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSettingsServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SettingsServiceClient {
	mock := &SettingsServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
