// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	mock "github.com/stretchr/testify/mock"

	version "github.com/argoproj/argo-cd/v2/pkg/apiclient/version"
)

// VersionServiceClient is an autogenerated mock type for the VersionServiceClient type
type VersionServiceClient struct {
	mock.Mock
}

// Version provides a mock function with given fields: ctx, in, opts
func (_m *VersionServiceClient) Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*version.VersionMessage, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *version.VersionMessage
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *version.VersionMessage); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*version.VersionMessage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewVersionServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewVersionServiceClient creates a new instance of VersionServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewVersionServiceClient(t mockConstructorTestingTNewVersionServiceClient) *VersionServiceClient {
	mock := &VersionServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
