apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: appstudio-controller-manager
  name: gitops-appstudio-service-controller-manager-metrics-service
  namespace: gitops
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  # - name: http-metrics
  #   port: 8080
  #   protocol: TCP
  #   targetPort: 8080
  - name: metrics
    protocol: TCP
    port: 8443
    targetPort: https
  selector:
    control-plane: appstudio-controller-manager
  sessionAffinity: None
  type: ClusterIP
