{
 "title": "GitOps",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - max(process_start_time_seconds{job=\"gitops-core-service-controller-manager-metrics-service\"})"
      }
     ]
    },
    {
     "title": "Deployments",
     "type": "timeseries",
     "description": "Number of active and failed GitopsDeployments",
     "gridPos": { "h": 8, "w": 12, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "active_gitopsDeployments", "legendFormat": "Total" },
      { "expr": "gitopsDeployments_failures", "legendFormat": "Failed" }
     ]
    },
    {
     "title": "Operation CR",
     "type": "timeseries",
     "description": "Number Of operations CR on a cluster",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "number_of_operationsCR", "legendFormat": "Total" }
     ]
    }
   ]
  },
  {
   "title": "Appstudio Controller Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "WorkQueue",
     "type": "heatmap",
     "description": "workqueue_work_duration_seconds_bucket metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": " sum(rate(workqueue_work_duration_seconds_bucket{name=\"snapshotenvironmentbinding\"}[$interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "WorkQueue Count",
     "type": "timeseries",
     "description": "workqueue_work_duration_seconds_count metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(workqueue_work_duration_seconds_count{name=\"snapshotenvironmentbinding\"}[$interval]))",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "WorkQueue Depth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(workqueue_depth{name=\"snapshotenvironmentbinding\"})",
       "legendFormat": "Depth"
      }
     ]
    },
    {
     "title": "Controller runtime - Reconcile Errors",
     "type": "timeseries",
     "description": "controller_runtime_reconcile_errors_total metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(controller_runtime_reconcile_errors_total{controller=\"snapshotenvironmentbinding\"}[$interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Controller runtime - Reconcile time",
     "type": "heatmap",
     "description": "controller_runtime_reconcile_time_* metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"snapshotenvironmentbinding\"}[$interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Controller runtime - Concurrent reconciles",
     "type": "timeseries",
     "description": "Maximum number of concurrent reconciles per controller",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "controller_runtime_max_concurrent_reconciles{controller=\"snapshotenvironmentbinding\"}",
       "legendFormat": "concurrent reconciles"
      }
     ]
    },
    {
     "title": "WorkQueue unfinished work",
     "type": "timeseries",
     "description": "How many seconds of work has been done that is in progress and hasn't been observed by work_duration",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "workqueue_unfinished_work_seconds{name=\"snapshotenvironmentbinding\"}",
       "legendFormat": "unfinished work"
      }
     ]
    },
    {
     "title": "Controller runtime - Reconcile Total",
     "type": "timeseries",
     "description": "controller_runtime_reconcile_total metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(controller_runtime_reconcile_total{controller=\"snapshotenvironmentbinding\"}[$interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Controller runtime - Reconcile time count",
     "type": "timeseries",
     "description": "Controller runtime reconcile time count",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum(rate(controller_runtime_reconcile_time_seconds_count{controller=\"snapshotenvironmentbinding\"}[$interval]))",
       "legendFormat": "Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Argo CD Application Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_app_info{namespace=\"gitops-service-argocd\",health_status!=\"\"}) by (health_status)",
       "legendFormat": "{{health_status}}"
      }
     ]
    },
    {
     "title": "Sync Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_app_info{namespace=\"gitops-service-argocd\",health_status!=\"\"}) by (sync_status)",
       "legendFormat": "{{sync_status}}"
      }
     ]
    },
    {
     "title": "Percent Reconciled",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "gitops_argocd_apps_reconciled_percent",
       "legendFormat": "Percent Reconciled"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation DB Rows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster-agent",
     "type": "timeseries",
     "description": "Number of Operation DB rows from cluster-agent",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "operationDB_completedState", "legendFormat": "Completed" },
      { "expr": "operationDB_failedState", "legendFormat": "Failed" }
     ]
    },
    {
     "title": "Backend",
     "type": "timeseries",
     "description": "Number of Operation DB rows from backend",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "total_number_of_operationDB_rows",
       "legendFormat": "Total"
      },
      {
       "expr": "operationDB_rows_in_waiting_state",
       "legendFormat": "Waiting"
      },
      {
       "expr": "operationDB_rows_in_in_progress_state",
       "legendFormat": "In_Progress"
      },
      {
       "expr": "operationDB_rows_in_completed_state",
       "legendFormat": "Completed"
      },
      {
       "expr": "operationDB_rows_in_error_state",
       "legendFormat": "Failed"
      },
      {
       "expr": "total_operationDB_rows_in_complete_state",
       "legendFormat": "TotalCompleted"
      },
      {
       "expr": "operationDB_rows_in_non_complete_state",
       "legendFormat": "TotalNonCompleted"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Controller Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"gitops-appstudio-service-controller-manager-metrics-service\"}",
       "legendFormat": "memory"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"gitops-appstudio-service-controller-manager-metrics-service\"}[1m])",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"gitops-appstudio-service-controller-manager-metrics-service\"}",
       "legendFormat": "goroutines"
      }
     ]
    }
   ]
  },
  {
   "title": "Core Service Controller Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"gitops-core-service-controller-manager-metrics-service\"}",
       "legendFormat": "memory"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"gitops-core-service-controller-manager-metrics-service\"}[1m])",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"gitops-core-service-controller-manager-metrics-service\"}",
       "legendFormat": "goroutines"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Agent Controller Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"gitops-service-agent-controller-manager-metrics-service\"}",
       "legendFormat": "memory"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"gitops-service-agent-controller-manager-metrics-service\"}[1m])",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"gitops-service-agent-controller-manager-metrics-service\"}",
       "legendFormat": "goroutines"
      }
     ]
    }
   ]
  }
 ]
}