apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: component-a
  name: component-a
spec:

  # Service intentionally does not contain 'ports' field, here. This should be defined within the overlay.
  
  selector:
    app.kubernetes.io/name: component-a

