apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gitops-namespace.yaml

# APIExport(s) / APIResourceSchema(s)
# - ../../appstudio-controller/config/kcp-new
- ../../backend-shared/config/kcp-new

# AppStudio-controller RBAC
#- ../appstudio-controller-rbac

# Backend RBAC
- ../backend-rbac

# Cluster-agent RBAC
- ../cluster-agent-rbac

# Workloads
- ../controller-deployments
- ../postgresql-staging

# Route(s)
- ../routes

# Argo CD 
- argocd

# Replace ${ARGO_CD_NAMESPACE} in GitOps Service controller Deployments
patches:
- target:
    kind: Secret
    name: argocd-cluster-config
  patch: |-
    - op: replace
      path: /stringData/namespace
      value: gitops-service-argocd
- target:
    kind: Deployment
    name: managed-gitops-backend-service
    namespace: gitops
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/1/env/0/value
      value: gitops-service-argocd
- target:
    kind: Deployment
    name: managed-gitops-clusteragent-service
    namespace: gitops
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/1/env/0/value
      value: gitops-service-argocd
