apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/crd/overlays/stonesoup
- ../../base/gitops-namespace
- ../../base/cluster-scoped
- ../../../appstudio-controller/config/tmp-default-webhook-with-env
- ../../../backend/config/default-no-prometheus
- ../../../cluster-agent/config/default-no-prometheus
- ../../base/gitops-service-argocd/overlays/appstudio-staging-and-prod
- ../appstudio-staging-cluster/prometheus

patchesStrategicMerge:
- backend-deployment-patch.yaml
- cluster-agent-deployment-patch.yaml
- appstudio-controller-deployment-patch.yaml

# Uncomment to use a custom image:
# images:
#   - name: \${COMMON_IMAGE}
#     newName: quay.io/(your user name)/gitops-service
#     newTag: latest
