apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  resource.exclusions: |
    - apiGroups:
      - "*.kcp.dev"
      clusters:
      - "*"
      kinds:
      - "*"
