apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: gitops-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: 'quay.io/redhat-appstudio/pull-request-builds:mgiops-{{revision}}'
  pipelineRef:
    params:
      - name: bundle
        value: >-
          quay.io/konflux-ci/tekton-catalog/pipeline-core-services-docker-build:latest
      - name: name
        value: docker-build
      - name: kind
        value: Pipeline
    resolver: bundles
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
