---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: gitops-service-cluster-agent
  annotations:
    pipelinesascode.tekton.dev/on-event: "push"
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: git-url
      value: 'https://github.com/redhat-appstudio/managed-gitops'
    - name: revision
      value: "{{ revision }}"
    - name: output-image
      value: 'quay.io/redhat-appstudio/gitops-service:{{ revision }}'
    - name: path-context
      value: .
    - name: dockerfile
      value: Dockerfile
    - name: infra-deployment-update-script
      value: |
        sed -i -e 's|\(https://raw.githubusercontent.com/redhat-appstudio/managed-gitops/\)[^/]*\(/.*\)|\1{{ revision }}\2|' -e 's/\(newTag: \).*/\1{{ revision }}/' components/gitops/staging/kustomization.yaml
  pipelineRef:
    name: docker-build
    bundle: quay.io/redhat-appstudio/hacbs-core-service-templates-bundle:latest
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: app-studio-default-workspace
      subPath: gitops-service-push-{{ revision }}
