// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/redhat-appstudio/managed-gitops/backend/condition (interfaces: Conditions)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1alpha1 "github.com/redhat-appstudio/managed-gitops/backend-shared/apis/managed-gitops/v1alpha1"
)

// MockConditions is a mock of Conditions interface.
type MockConditions struct {
	ctrl     *gomock.Controller
	recorder *MockConditionsMockRecorder
}

// MockConditionsMockRecorder is the mock recorder for MockConditions.
type MockConditionsMockRecorder struct {
	mock *MockConditions
}

// NewMockConditions creates a new mock instance.
func NewMockConditions(ctrl *gomock.Controller) *MockConditions {
	mock := &MockConditions{ctrl: ctrl}
	mock.recorder = &MockConditionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConditions) EXPECT() *MockConditionsMockRecorder {
	return m.recorder
}

// FindCondition mocks base method.
func (m *MockConditions) FindCondition(arg0 *[]v1alpha1.GitOpsDeploymentCondition, arg1 v1alpha1.GitOpsDeploymentConditionType) (*v1alpha1.GitOpsDeploymentCondition, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCondition", arg0, arg1)
	ret0, _ := ret[0].(*v1alpha1.GitOpsDeploymentCondition)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// FindCondition indicates an expected call of FindCondition.
func (mr *MockConditionsMockRecorder) FindCondition(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCondition", reflect.TypeOf((*MockConditions)(nil).FindCondition), arg0, arg1)
}

// HasCondition mocks base method.
func (m *MockConditions) HasCondition(arg0 *[]v1alpha1.GitOpsDeploymentCondition, arg1 v1alpha1.GitOpsDeploymentConditionType) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasCondition", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasCondition indicates an expected call of HasCondition.
func (mr *MockConditionsMockRecorder) HasCondition(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasCondition", reflect.TypeOf((*MockConditions)(nil).HasCondition), arg0, arg1)
}

// SetCondition mocks base method.
func (m *MockConditions) SetCondition(arg0 *[]v1alpha1.GitOpsDeploymentCondition, arg1 v1alpha1.GitOpsDeploymentConditionType, arg2 v1alpha1.GitOpsConditionStatus, arg3 v1alpha1.GitOpsDeploymentReasonType, arg4 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCondition", arg0, arg1, arg2, arg3, arg4)
}

// SetCondition indicates an expected call of SetCondition.
func (mr *MockConditionsMockRecorder) SetCondition(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCondition", reflect.TypeOf((*MockConditions)(nil).SetCondition), arg0, arg1, arg2, arg3, arg4)
}
