
resources:
- cm-env-config-map.yaml
# - (resources will be applied in all environments, though environments may modify these via patches)

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
