apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: cluster-agent-controller-manager
  name: controller-manager-metrics-service
  namespace: gitops
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    control-plane: cluster-agent-controller-manager
  sessionAffinity: None
  type: ClusterIP
