apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
-  https://raw.githubusercontent.com/argoproj/argo-cd/$ARGO_CD_VERSION/manifests/install.yaml

namespace: $ARGO_CD_NAMESPACE

patchesStrategicMerge:
- |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:         
    name: argocd-application-controller
  subjects:         
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: $ARGO_CD_NAMESPACE

- |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:         
    name: argocd-server
  subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: $ARGO_CD_NAMESPACE

